export const ltx = {
  limInf: '\\lim\\limits_{x\\rightarrow\\infin}',
  limPlMnInf: '\\lim\\limits_{x\\rightarrow\\plusmn\\infin}',
  limA: '\\lim\\limits_{x\\rightarrow a}',
  lim0: '\\lim\\limits_{x\\rightarrow 0}',
  lim0Pl: '\\lim\\limits_{x\\rightarrow 0^+}',
  iss: '\\Leftrightarrow ',
  Larr: '\\Larr ',
  Rarr: '\\Rarr ',
  rarr: '\\rarr',
  frac: '\\frac{a}{b}',
  dfrac: '\\dfrac{a}{b}',
  sqrt: '\\sqrt{a+b}',
  pow: 'a^b',
  inf: '\\infin ',
  log: '^a\\log{x}',
  ln: '\\ln{x}',
  abs: '|x|',
};
